import { StatusBar } from 'expo-status-bar';
import { ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useReadingProgress } from '@/context/reading-progress';

export default function ReadScreen() {
  const { totals } = useReadingProgress();
  return <View style={s.screen}><StatusBar style="light" /><SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.content}><Text style={s.kicker}>YOUR LIBRARY</Text><Text style={s.title}>Read</Text><View style={s.card}><Text style={s.cardKicker}>THIS SESSION</Text><Text style={s.cardTitle}>Continue your reading</Text><Text style={s.copy}>Choose a book and chapter from Home. Your reading progress is saved for this session.</Text><View style={s.line}><View style={[s.fill,{width:`${totals.chapters ? totals.completed * 100 / totals.chapters : 0}%`}]} /></View><Text style={s.progress}>{totals.completed} of {totals.chapters} chapters completed</Text></View><Text style={s.heading}>Your marks</Text><View style={s.summary}><Text style={s.summaryValue}>{totals.highlighted}</Text><Text style={s.summaryLabel}>sentences highlighted</Text></View></ScrollView></SafeAreaView></View>;
}
const s=StyleSheet.create({screen:{flex:1,backgroundColor:'#242221'},safe:{flex:1},content:{padding:20},kicker:{marginTop:10,color:'#D7A94B',fontSize:10,fontWeight:'800',letterSpacing:1.5},title:{marginTop:8,color:'#FBF9F4',fontFamily:'Georgia',fontSize:40},card:{marginTop:25,padding:22,borderRadius:24,backgroundColor:'#F1E6CF'},cardKicker:{color:'#9A701D',fontSize:10,fontWeight:'800',letterSpacing:1.3},cardTitle:{marginTop:9,color:'#292827',fontFamily:'Georgia',fontSize:26},copy:{marginTop:10,color:'#6C655B',fontSize:13,lineHeight:19},line:{height:8,marginTop:22,borderRadius:7,backgroundColor:'#DDD0B8',overflow:'hidden'},fill:{height:'100%',backgroundColor:'#C79832'},progress:{marginTop:8,color:'#77716A',fontSize:11},heading:{marginTop:27,color:'#FBF9F4',fontFamily:'Georgia',fontSize:21},summary:{marginTop:12,padding:18,borderRadius:18,borderWidth:1,borderColor:'#514D48',backgroundColor:'#302E2B'},summaryValue:{color:'#E8C77F',fontSize:29,fontWeight:'800'},summaryLabel:{marginTop:2,color:'#AAA39A',fontSize:12}});
